name: 'Release pull request'
description: 'It creates release pull request'
inputs:
  repo-token:
    required: true
    description: 'Repository Github token'
  changelog-scopes:
    required: true
    description: 'Scopes which will be used in changelog (the first scope will be used as default for commit messages without scope)'
  base-branch:
    required: false
    default: master
    description: 'Base branch where you want to do release pull request'
  create-pull-request:
    required: false
    default: true
    description: 'Whether to create release pull request'
  compare-method:
    required: false
    default: branch
    description: 'Fetch commit history, either by diff of head and branch or latest tag and HEAD'
  open-ai-token:
    required: false
    description: 'Experimental feature: OpenAI token for improving changelog using text model'
outputs:
  changelog:
    description: 'Changelog content'
  changelogFileDestination:
    description: 'Path to changelog file stored in file-system'
runs:
  using: 'node16'
  main: 'dist/index.js'
