name: 'Release pull request'
description: 'It creates release pull request'
inputs:
  repo-token:
    required: true
    description: 'Repository Github token'
  changelog-scopes:
    required: true
    description: 'Scopes which will be used in changelog (the first scope will be used as default for commit messages without scope)'
  base-branch:
    required: false
    default: master
    description: 'Base branch where you want to do release pull request'
  create-pull-request:
    required: false
    default: true
    description: Whether to create release pull request
outputs:
  changelog:
    description: Changelog content
runs:
  using: 'node12'
  main: 'dist/index.js'
