# For more info see: https://github.com/apify/pull-request-toolkit-action/
name: Test

on:
  workflow_dispatch:

  push:
    branches:
      - test/cc

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: 'dist/index.js'
