name: Test the action

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-release-pr-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test Release pull request action
        uses: ./
        with:
          github-token: ${{ secrets.githubToken }}
          changelog-scopes: '{ "Action": ["action"] }'
          base-branch: 'main'
          create-release-pull-request: true
          changelog-method: commits_compare
          open-ai-token: ${{ secrets.openAiToken }}
