# For more info see: https://github.com/apify/pull-request-toolkit-action/
name: Test

on:
  workflow_dispatch:

  push:
    branches:
      - test/cc

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: run
        run: 'node dist/index.js'
        with:
          github_token: 'FOO'
